name: Lint Check

on:
  push:
    branches:
      - main
      - refacto_and_ci
  pull_request:
    branches:
      - main
      - refacto_and_ci

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (JavaScript/TypeScript)
        run: npx eslint src

      - name: Run Stylelint (SCSS)
        run: npx stylelint "**/*.scss"

      - name: Run HTMLHint (HTML)
        run: npx htmlhint "**/*.html"
